### ISSUE TITLE
A lot of suspicious errors

### ISSUE THREAD

**Issue by JustAHippo** [X-SLAYER/SLAYER-LEECHER#2]
I am genuinely concerned about this program since it errored due to being unable to contact an API for verification on the precompiled build
The precompiled debug version in the github flags my antivirus more times than my parents told me they were disappointed in me
And the build failed on release any CPU

**Comment by JustAHippo** [comment]
https://www.virustotal.com/gui/file/6a26709ffb1e62bcd27023a2b906e20ee20e1c4106cbea410a5d77acc5296b0c
that's a virus total of the release btw

**Comment by VirtualyMichael** [comment]
Thanks man there are versions out there that are legit its just hard to find a good one

**Comment by Fisheiyy** [comment]
> I am genuinely concerned about this program since it errored due to being unable to contact an API for verification on the precompiled build The precompiled debug version in the github flags my antivirus more times than my parents told me they were disappointed in me And the build failed on release any CPU

of course it will flag your antivirus idiot why would it not?

**Comment by RealRainn** [comment]
> https://www.virustotal.com/gui/file/6a26709ffb1e62bcd27023a2b906e20ee20e1c4106cbea410a5d77acc5296b0c that's a virus total of the release btw

its literally open source bro
